# Generated by Django 4.2.1 on 2023-06-05 12:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_game_max_number_of_teams_quiz_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameregistration',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
